Repository testit-tms/migrators, pull requests merged in 2023-11, with the labels that each got.

#22 Added TestLinkExporter.
  .github/workflows/validate.yaml
  Migrators/Migrators.sln
  Migrators/TestLinkExporter/App.cs
  Migrators/TestLinkExporter/Client/Client.cs
  Migrators/TestLinkExporter/Client/IClient.cs
  Migrators/TestLinkExporter/Models/SectionData.cs
  Migrators/TestLinkExporter/Models/TestLinkAttachment.cs
  Migrators/TestLinkExporter/Models/TestLinkProject.cs
  Migrators/TestLinkExporter/Models/TestLinkStep.cs
  Migrators/TestLinkExporter/Models/TestLinkSuite.cs
  Migrators/TestLinkExporter/Models/TestLinkTestCase.cs
  Migrators/TestLinkExporter/Program.cs
  Migrators/TestLinkExporter/Readme.md
  Migrators/TestLinkExporter/Services/AttachmentService.cs
  Migrators/TestLinkExporter/Services/ExportService.cs
  Migrators/TestLinkExporter/Services/IAttachmentService.cs
  Migrators/TestLinkExporter/Services/IExportService.cs
  Migrators/TestLinkExporter/Services/ISectionService.cs
  Migrators/TestLinkExporter/Services/IStepService.cs
  Migrators/TestLinkExporter/Services/ITestCaseService.cs
  Migrators/TestLinkExporter/Services/SectionService.cs
  Migrators/TestLinkExporter/Services/StepService.cs
  Migrators/TestLinkExporter/Services/TestCaseService.cs
  Migrators/TestLinkExporter/TestLinkExporter.csproj
  Migrators/TestLinkExporter/testlink.config.json
  Migrators/TestLinkExporterTests/AttachmentServiceTests.cs
  Migrators/TestLinkExporterTests/ExportServiceTests.cs
  Migrators/TestLinkExporterTests/SectionServiceTests.cs
  Migrators/TestLinkExporterTests/StepServiceTests.cs
  Migrators/TestLinkExporterTests/TestCaseServiceTests.cs
  Migrators/TestLinkExporterTests/TestLinkExporterTests.csproj
  Migrators/TestLinkExporterTests/Usings.cs
  README.md
Labels: documentation, enhancement

#23 Fixed release action
  .github/workflows/release.yaml
Labels: bug

#24 Fixed project
  Migrators/TestLinkExporter/TestLinkExporter.csproj
Labels: bug

#26 Added TestCollab Exporter
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
  Migrators/Migrators.sln
  Migrators/TestCollabExporter/App.cs
  Migrators/TestCollabExporter/Client/Client.cs
  Migrators/TestCollabExporter/Client/IClient.cs
  Migrators/TestCollabExporter/Models/AttributeData.cs
  Migrators/TestCollabExporter/Models/DescriptionData.cs
  Migrators/TestCollabExporter/Models/SectionData.cs
  Migrators/TestCollabExporter/Models/SharedStepData.cs
  Migrators/TestCollabExporter/Models/TestCollabCompany.cs
  Migrators/TestCollabExporter/Models/TestCollabCustomField.cs
  Migrators/TestCollabExporter/Models/TestCollabProjects.cs
  Migrators/TestCollabExporter/Models/TestCollabSharedStep.cs
  Migrators/TestCollabExporter/Models/TestCollabSuite.cs
  Migrators/TestCollabExporter/Models/TestCollabTestCase.cs
  Migrators/TestCollabExporter/Program.cs
  Migrators/TestCollabExporter/Readme.md
  Migrators/TestCollabExporter/Services/AttachmentService.cs
  Migrators/TestCollabExporter/Services/AttributeService.cs
  Migrators/TestCollabExporter/Services/ExportService.cs
  Migrators/TestCollabExporter/Services/IAttachmentService.cs
  Migrators/TestCollabExporter/Services/IAttributeService.cs
  Migrators/TestCollabExporter/Services/IExportService.cs
  Migrators/TestCollabExporter/Services/ISectionService.cs
  Migrators/TestCollabExporter/Services/ISharedStepService.cs
  Migrators/TestCollabExporter/Services/ITestCaseService.cs
  Migrators/TestCollabExporter/Services/SectionService.cs
  Migrators/TestCollabExporter/Services/SharedStepService.cs
  Migrators/TestCollabExporter/Services/TestCaseService.cs
  Migrators/TestCollabExporter/TestCollabExporter.csproj
  Migrators/TestCollabExporter/testcollab.config.json
  Migrators/TestCollabExporterTests/AttachmentServiceTests.cs
  Migrators/TestCollabExporterTests/AttributeServiceTests.cs
  Migrators/TestCollabExporterTests/ExportServiceTests.cs
  Migrators/TestCollabExporterTests/SectionServiceTests.cs
  Migrators/TestCollabExporterTests/SharedStepServiceTests.cs
  Migrators/TestCollabExporterTests/TestCaseServiceTests.cs
  Migrators/TestCollabExporterTests/TestCollabExporterTests.csproj
  Migrators/TestCollabExporterTests/Usings.cs
  README.md
Labels: enhancement

#28 Fixed Azure Exporter
  Migrators/AllureExporter/App.cs
  Migrators/AzureExporter/App.cs
  Migrators/AzureExporter/Client/Client.cs
  Migrators/AzureExporter/Services/AttributeService.cs
  Migrators/AzureExporter/Services/LinkService.cs
  Migrators/AzureExporter/Services/ParameterService.cs
  Migrators/AzureExporter/Services/SharedStepService.cs
  Migrators/AzureExporter/Services/TestCaseService.cs
  Migrators/AzureExporterTests/ParameterServiceTests.cs
  Migrators/TestLinkExporter/TestLinkExporter.csproj
Labels: bug

#30 Fixed getting deleted shared steps.
  Migrators/AzureExporter/Services/StepService.cs
  Migrators/AzureExporterTests/StepServiceTests.cs
Labels: bug

#29 Fixed converting of iterations.
  Migrators/AzureExporter/Services/ParameterService.cs
Labels: bug

#32 Added SpiraTest Exporter
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
  Migrators/Migrators.sln
  Migrators/SpiraTestExporter/App.cs
  Migrators/SpiraTestExporter/Client/Client.cs
  Migrators/SpiraTestExporter/Client/IClient.cs
  Migrators/SpiraTestExporter/Models/ArtifactType.cs
  Migrators/SpiraTestExporter/Models/AttributeData.cs
  Migrators/SpiraTestExporter/Models/Constants.cs
  Migrators/SpiraTestExporter/Models/SectionData.cs
  Migrators/SpiraTestExporter/Models/SpiraAttachment.cs
  Migrators/SpiraTestExporter/Models/SpiraFolder.cs
  Migrators/SpiraTestExporter/Models/SpiraPriority.cs
  Migrators/SpiraTestExporter/Models/SpiraProject.cs
  Migrators/SpiraTestExporter/Models/SpiraStatus.cs
  Migrators/SpiraTestExporter/Models/SpiraStep.cs
  Migrators/SpiraTestExporter/Models/SpiraStepParameter.cs
  Migrators/SpiraTestExporter/Models/SpiraTest.cs
  Migrators/SpiraTestExporter/Models/SpiraTestCaseParameter.cs
  Migrators/SpiraTestExporter/Models/TestCaseData.cs
  Migrators/SpiraTestExporter/Program.cs
  Migrators/SpiraTestExporter/Readme.md
  Migrators/SpiraTestExporter/Services/AttachmentService.cs
  Migrators/SpiraTestExporter/Services/AttributeService.cs
  Migrators/SpiraTestExporter/Services/ExportService.cs
  Migrators/SpiraTestExporter/Services/IAttachmentService.cs
  Migrators/SpiraTestExporter/Services/IAttributeService.cs
  Migrators/SpiraTestExporter/Services/IExportService.cs
  Migrators/SpiraTestExporter/Services/ISectionService.cs
  Migrators/SpiraTestExporter/Services/ITestCaseService.cs
  Migrators/SpiraTestExporter/Services/SectionService.cs
  Migrators/SpiraTestExporter/Services/TestCaseService.cs
  Migrators/SpiraTestExporter/SpiraTestExporter.csproj
  Migrators/SpiraTestExporter/spiratest.config.json
  Migrators/SpiraTestExporterTests/AttachmentServiceTests.cs
  Migrators/SpiraTestExporterTests/AttributeServiceTests.cs
  Migrators/SpiraTestExporterTests/SectionServiceTests.cs
  Migrators/SpiraTestExporterTests/SpiraTestExporterTests.csproj
  Migrators/SpiraTestExporterTests/TestCaseServiceTests.cs
  Migrators/SpiraTestExporterTests/Usings.cs
  Migrators/TestCollabExporter/Client/Client.cs
  README.md
Labels: enhancement
