Repository testit-tms/migrators, pull requests merged in 2025-09, with the labels that each got.

#126 fix: TMS-34861: add the building for the apple M4.
  .github/workflows/release.yaml
Labels: bug, enhancement

#127 fix: TMS-34861: add the building for the apple M4.
  Migrators/AllureExporter/AllureExporter.csproj
  Migrators/AzureExporter/AzureExporter.csproj
  Migrators/HPALMExporter/HPALMExporter.csproj
  Migrators/Importer/Importer.csproj
  Migrators/Models/Models.csproj
  Migrators/PractiTestExporter/PractiTestExporter.csproj
  Migrators/QaseExporter/QaseExporter.csproj
  Migrators/SpiraTestExporter/SpiraTestExporter.csproj
  Migrators/TestCollabExporter/TestCollabExporter.csproj
  Migrators/TestLinkExporter/TestLinkExporter.csproj
  Migrators/TestRailExporter/TestRailExporter.csproj
  Migrators/TestRailXmlExporter/TestRailXmlExporter.csproj
  Migrators/XRayExporter/XRayExporter.csproj
  Migrators/ZephyrScaleExporter/ZephyrScaleExporter.csproj
  Migrators/ZephyrScaleServerExporter/ZephyrScaleServerExporter/ZephyrScaleServerExporter.csproj
  Migrators/ZephyrSquadExporter/ZephyrSquadExporter.csproj
  Migrators/ZephyrSquadServerExporter/ZephyrSquadServerExporter.csproj
Labels: bug

#128 feat: support azure 2019 with 16.153.0
  .github/workflows/build-project.yml
  .github/workflows/check-release-allure.yml
  .github/workflows/check-release-azure.yml
  .github/workflows/check-release-hpalm.yml
  .github/workflows/check-release-importer.yml
  .github/workflows/check-release-practitest.yml
  .github/workflows/check-release-qase.yml
  .github/workflows/check-release-spiratest.yml
  .github/workflows/check-release-test-collab.yml
  .github/workflows/check-release-testlink.yml
  .github/workflows/check-release-testrail.yml
  .github/workflows/check-release-xray.yml
  .github/workflows/check-release-zephyr-scale.yml
  .github/workflows/check-release-zephyr-squad.yml
  .github/workflows/check-release.yml
  .github/workflows/rc-validate.yml
  .github/workflows/release.yaml
  .github/workflows/test-workflow.yaml
  .github/workflows/validate-azure.yaml
  .github/workflows/validate-hpalm.yaml
  .github/workflows/validate-practitest.yaml
  .github/workflows/validate-spira.yaml
  .github/workflows/validate-testcollab.yaml
  .github/workflows/validate-testlink.yaml
  .github/workflows/validate-xray.yaml
  .github/workflows/validate-zephyr-squad.yaml
  .github/workflows/validate-zephyr.yaml
  .github/workflows/validate.yaml
  .gitignore
  Migrators/AzureExporter/.gitignore
  Migrators/AzureExporter/AzureExporter.csproj
  Migrators/AzureExporter/Services/AttachmentService.cs
  Migrators/ImporterTests/BaseWorkItemServiceTests.cs
  Migrators/ImporterTests/SharedStepServiceTests.cs
  Migrators/ImporterTests/TestCaseServiceTests.cs
Labels: enhancement
